name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-20.04

          - os: ubuntu-20.04
            appimage: true

          - os: windows-2022
            name: "Windows-x86_64"

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x

    - name: Restore dependencies
      run: dotnet restore

    - name: mkdir
      run: mkdir ./artifact

    - name: Build
      run: dotnet publish ./ChlorineSharp/ChlorineSharp.csproj -c Release -o ./artifact

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2
      with:
        name: ChlorineSharp - ${{ matrix.os }}
        path: artifact
